---
- name: Collect commands
  hosts: eos
  connection: network_cli
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Collect commands
      import_role:
        name: eos_snapshot