---
hostname: sw3
loopback: 3.3.3.3
interface_vlan:
  - interface: Vlan30
    ip: 30.30.30.2
    subnet: 24    
  - interface: Vlan40
    ip: 40.40.40.1
    subnet: 24

ospf: 1
ospf_network:
  - ip: 30.30.30.2
    area: 10
  - ip: 40.40.40.1
    area: 10   

## ansible manual 대로 작성, vlan 활성화한다. 
vlans: 
  - vlan_id: 30
    state: active
  - vlan_id: 40
    state: active